package org.aion.avm.internal;

import org.aion.avm.arraywrapper.ObjectArray;


/**
 * Used by the ABIEncoder to instantiate the higher-order arrays which are not part of the hard-coded shadow class library
 * and must be generated by some mechanism from outside the runtime package.
 */
public interface IABISupport {
    ObjectArray construct2DByteArray(byte[][] nativeArray);

    ObjectArray construct2DBooleanArray(boolean[][] nativeArray);

    ObjectArray construct2DCharArray(char[][] nativeArray);

    ObjectArray construct2DShortArray(short[][] nativeArray);

    ObjectArray construct2DIntArray(int[][] nativeArray);

    ObjectArray construct2DLongArray(long[][] nativeArray);

    ObjectArray construct2DFloatArray(float[][] nativeArray);

    ObjectArray construct2DDoubleArray(double[][] nativeArray);

    ObjectArray construct1DStringArray(org.aion.avm.shadow.java.lang.String[] shadowArray);
}
