package org.aion.avm.internal;

/**
 * Represent an exception which is generated by user's code but propagates to the AVM.
 */
public class UncaughtException extends AvmException {

    public UncaughtException(Throwable cause) {
        super(cause);
    }
}
